// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvOUE9uPefoYi0eb-134n6EsDf13dkgeY',
    appId: '1:252287736025:web:8e7ded485eec1df32546c8',
    messagingSenderId: '252287736025',
    projectId: 'research-391d9',
    authDomain: 'research-391d9.firebaseapp.com',
    databaseURL: 'https://research-391d9-default-rtdb.firebaseio.com',
    storageBucket: 'research-391d9.appspot.com',
    measurementId: 'G-7W6FGYNGVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVhSmfjLOu5awcvb0FWxKolqXulv_ghbI',
    appId: '1:252287736025:android:cb37bbf2f4571dfd2546c8',
    messagingSenderId: '252287736025',
    projectId: 'research-391d9',
    databaseURL: 'https://research-391d9-default-rtdb.firebaseio.com',
    storageBucket: 'research-391d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7SGFsoZym9aG74LLmnMFzKTWD9TMEhD8',
    appId: '1:252287736025:ios:b61d7a9ae40ac22b2546c8',
    messagingSenderId: '252287736025',
    projectId: 'research-391d9',
    databaseURL: 'https://research-391d9-default-rtdb.firebaseio.com',
    storageBucket: 'research-391d9.appspot.com',
    androidClientId: '252287736025-kgrqqood2o1sf0i1bduur2dho9cv3fro.apps.googleusercontent.com',
    iosClientId: '252287736025-b4v4ufpji2ek297vjgafbp6madljri11.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7SGFsoZym9aG74LLmnMFzKTWD9TMEhD8',
    appId: '1:252287736025:ios:92411040fa1e5ba82546c8',
    messagingSenderId: '252287736025',
    projectId: 'research-391d9',
    databaseURL: 'https://research-391d9-default-rtdb.firebaseio.com',
    storageBucket: 'research-391d9.appspot.com',
    androidClientId: '252287736025-kgrqqood2o1sf0i1bduur2dho9cv3fro.apps.googleusercontent.com',
    iosClientId: '252287736025-dqgre6e2ve3cb16ismqgn0i25ltn4qfk.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalapp.RunnerTests',
  );
}
